# Generated by Django 4.2.7 on 2026-02-17 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_lessonprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название экзамена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('passing_score', models.PositiveIntegerField(default=70, verbose_name='Проходной балл (%)')),
                ('allow_retake', models.BooleanField(default=False, verbose_name='Разрешить пересдачу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('choice', 'Выбор ответа'), ('text', 'Ручной ввод')], default='choice', max_length=10, verbose_name='Тип вопроса')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Баллы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.exam', verbose_name='Экзамен')),
            ],
            options={
                'verbose_name': 'Вопрос экзамена',
                'verbose_name_plural': 'Вопросы экзамена',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('time_limit', models.PositiveIntegerField(default=0, help_text='0 - без ограничения', verbose_name='Лимит времени (минут)')),
                ('passing_score', models.PositiveIntegerField(default=70, verbose_name='Проходной балл (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Баллы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы теста',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.testquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Набрано баллов')),
                ('passed', models.BooleanField(default=False, verbose_name='Пройден?')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Попытка теста',
                'verbose_name_plural': 'Попытки тестов',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.testattempt', verbose_name='Попытка')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.testquestion', verbose_name='Вопрос')),
                ('selected_options', models.ManyToManyField(to='courses.testchoiceoption', verbose_name='Выбранные варианты')),
            ],
            options={
                'verbose_name': 'Ответ на тест',
                'verbose_name_plural': 'Ответы на тесты',
            },
        ),
        migrations.CreateModel(
            name='ExamTextAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(help_text='Можно указать несколько вариантов через |', max_length=500, verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_answers', to='courses.examquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Эталонный ответ (текст)',
                'verbose_name_plural': 'Эталонные ответы (текст)',
            },
        ),
        migrations.CreateModel(
            name='ExamChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.examquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа (экзамен)',
                'verbose_name_plural': 'Варианты ответов (экзамен)',
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Набрано баллов')),
                ('passed', models.BooleanField(default=False, verbose_name='Пройден?')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.exam', verbose_name='Экзамен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Попытка экзамена',
                'verbose_name_plural': 'Попытки экзаменов',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='Текстовый ответ')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.examattempt', verbose_name='Попытка')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.examquestion', verbose_name='Вопрос')),
                ('selected_options', models.ManyToManyField(blank=True, to='courses.examchoiceoption', verbose_name='Выбранные варианты')),
            ],
            options={
                'verbose_name': 'Ответ на экзамен',
                'verbose_name_plural': 'Ответы на экзамены',
            },
        ),
    ]
